<?php

namespace AQM\ArtBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticlesByCategorie($categorie)
    {
        $queryBuilder = $this->createQueryBuilder('a');
        $queryBuilder
            ->where($queryBuilder->expr()->eq('a.categorie', $categorie->getId()));
        return $queryBuilder->getQuery()->getResult();
    }
}
