aqm_art_homepage:
    path:     /
    defaults: { _controller: AQMArtBundle:Acceuil:index }

aqm_art_admin_home:
    path:     /admin
    defaults: { _controller: AQMArtBundle:Admin:index }

aqm_art_admin_profil_edit:
    path:     /admin/profil/edit
    defaults: { _controller: AQMArtBundle:Admin:profil }

aqm_art_categories:
    path:     /categories
    defaults: { _controller: AQMArtBundle:Categorie:index }

aqm_art_categories_add:
    path:     /categories/add
    defaults: { _controller: AQMArtBundle:Categorie:add }

aqm_art_categories_delete:
    path:     /categories/delete/{id}
    defaults: { _controller: AQMArtBundle:Categorie:delete }

aqm_art_categories_edit:
    path:     /categories/edit/{id}
    defaults: { _controller: AQMArtBundle:Categorie:edit }

aqm_art_articles:
    path:     /articles
    defaults: { _controller: AQMArtBundle:Article:index }
