aqm_art_homepage:
    path:     /
    defaults: { _controller: AQMArtBundle:Acceuil:index }

aqm_art_admin_home:
    path:     /admin
    defaults: { _controller: AQMArtBundle:Admin:index }

aqm_art_admin_profil_edit:
    path:     /admin/profil/edit
    defaults: { _controller: AQMArtBundle:Admin:profil }

aqm_art_categories:
    path:     admin/categories
    defaults: { _controller: AQMArtBundle:Categorie:index }

aqm_art_categories_add:
    path:     admin/categories/add
    defaults: { _controller: AQMArtBundle:Categorie:add }

aqm_art_categories_delete:
    path:     admin/categories/delete/{id}
    defaults: { _controller: AQMArtBundle:Categorie:delete }

aqm_art_categories_edit:
    path:     admin/categories/edit/{id}
    defaults: { _controller: AQMArtBundle:Categorie:edit }

aqm_art_articles:
    path:     admin/articles
    defaults: { _controller: AQMArtBundle:Article:index }

aqm_art_articles_add:
    path:     admin/articles/add
    defaults: { _controller: AQMArtBundle:Article:add }

aqm_art_articles_delete:
    path:     admin/articles/delete/{id}
    defaults: { _controller: AQMArtBundle:Article:delete }

aqm_art_articles_edit:
    path:     admin/articles/edit/{id}
    defaults: { _controller: AQMArtBundle:Article:edit }

aqm_art_articles_view:
    path:     /view/{slug}
    defaults: { _controller: AQMArtBundle:Article:view }
